version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: jewelry-workshop-db
    environment:
      POSTGRES_DB: jewelry_workshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 197326
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - workshop-net

  app:
    build: .
    container_name: jewelry-workshop-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jewelry_workshop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 197326
      APP_JWT_SECRET: LCiw+ElTEH1oiQYUPm+1qkvCaCbP6Lpe1eLsKh8Lpgi02gcvWlRpI5OxULIVIVwlp0+615OtoNimgmzp83cWew==
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - workshop-net

volumes:
  postgres_data:

networks:
  workshop-net:
    driver: bridge